services:

  app:
    container_name: metrics-consumer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_SKIP_TESTS=true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/metricsbase
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8866:8866
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: metrics-db
    image: postgres:15
    environment:
      - POSTGRES_DB=metricsbase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 26262:5432
    restart: unless-stopped
