services:

  user-db:
    container_name: user-db
    image: postgres:15
    environment:
      - POSTGRES_DB=userbase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 8225:5432
    restart: unless-stopped