server:
  port: 8224

spring:
  application:
    name: security-jwt
  datasource:
    url: jdbc:postgresql://localhost:8225/userbase
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: fdsf43fd21Sd3r2DF43tgtdfgbRESDSFGsfrfwfsdsgbyghrfg3fdsf
  expiration:
    token: 60000
    refresh: 300000

logging:
  level:
    org:
      springframework:
        security: TRACE
