services:

  db:
    container_name: timedb
    image: postgres:15
    environment:
      - POSTGRES_DB=timebase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 24242:5432
    restart: unless-stopped