services:

  app:
    container_name: time-tracker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_SKIP_TESTS=true
    ports:
      - 8885:8080
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: timedb
    image: postgres:15
    environment:
      - POSTGRES_DB=timebase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 24242:5432
    restart: unless-stopped